import next from '@munaxa/config-eslint/next.js';

import standards from '../../tooling/eslint/standards.mjs';

/** @type {import('eslint').Linter.Config[]} */
export default [
  // Generated by the framework and regenerated on every build — not ours to lint or to fix.
  { ignores: ['.next/**', 'next-env.d.ts'] },
  ...next,
  ...standards,
];
