-- Employment — the relationship between a person and the tenant's workforce (Phase 5).
--
-- Six tables, and the row-level security that isolates every one of them (ADR-0030). The policies
-- are created here, in the migration that creates the tables, rather than in a later "hardening"
-- step: a table that exists for one deployment without its policy is a table that leaked for that
-- deployment, and applying the policy afterwards does not un-leak it.
--
-- Four decisions in this file are the ones a reviewer should challenge.
--
--   * There is **no unit, position or cost-centre column on `employment`**. A person's placement
--     in the organization changes, and where they sat when a decision was taken stays answerable
--     forever. So placement lives entirely in `employment_assignment`, on a timeline (AD-005). A
--     convenience column here would be a second answer, and the second answer is the stale one.
--
--   * **`employment_number` is generated by this product and never supplied by a caller.** The
--     customer's own reference travels beside it in `external_employee_number`, so a migration
--     keeps its legacy numbers without either of them pretending to be the person's identity
--     (AD-002, ADR-0039). It is immutable, and it is never reused after an employment ends.
--
--   * **A person may hold many employments, and only one open at a time.** Rehire is a new
--     employment with a new number, never an edited old one (AD-004). The partial unique index on
--     `(tenant_id, person_id) where status <> 'ended'` is what makes a duplicated create fail
--     deterministically rather than quietly producing a second employment for one human being —
--     and dropping that one index is the whole of what enabling concurrent employments later
--     requires.
--
--   * **There is no work-location column.** An organizational unit and a physical place of work
--     are different concepts, and this product holds no authoritative model of the second. A
--     column pointed at `unit_id` would be a false relationship recorded as a true one. The
--     concept is absent and the extension point is named — ADR-0041.

-- ---------------------------------------------------------------------------------------------
-- The counter employment numbers are drawn from.
--
-- A table rather than a PostgreSQL sequence, and neither reason is stylistic: a sequence is not
-- tenant-scoped, and a sequence is not transactional — a create that rolled back would consume a
-- number and leave a permanent, unexplainable gap in a customer's employee numbering.
-- ---------------------------------------------------------------------------------------------
create table employment_number_sequence (
  id          uuid primary key default app_uuid_v7(),
  tenant_id   uuid not null,
  series_key  varchar(32) not null,
  next_value  integer not null,
  created_at  timestamptz(6) not null,
  created_by  varchar(255) not null,
  updated_at  timestamptz(6) not null,
  updated_by  varchar(255) not null,
  deleted_at  timestamptz(6),
  deleted_by  varchar(255),
  version     integer not null,
  constraint employment_number_sequence_value_check check (next_value > 0)
);

create unique index employment_number_sequence_series_key
  on employment_number_sequence (tenant_id, series_key)
  where deleted_at is null;

-- ---------------------------------------------------------------------------------------------
-- The employment itself.
-- ---------------------------------------------------------------------------------------------
create table employment (
  id                       uuid primary key default app_uuid_v7(),
  tenant_id                uuid not null,
  person_id                uuid not null,
  employment_number        varchar(64) not null,
  external_employee_number varchar(64),
  status                   varchar(32) not null,
  -- Tenant or country-pack codes. Which employment classifications exist is a statutory and
  -- cultural question, and a list shipped here would be a business rule about labour hardcoded in
  -- a schema (00B).
  employment_type_code     varchar(64) not null,
  employment_category_code varchar(64),
  employment_class_code    varchar(64),
  -- Dates, not timestamps. A hire date is the same date in Riyadh and in London; stored as an
  -- instant it shifts across a zone boundary, and a start date that moves by a day changes a
  -- probation end, a notice period and — in several of this product's markets — an end-of-service
  -- entitlement.
  original_hire_date       date not null,
  start_date               date not null,
  end_date                 date,
  end_reason_code          varchar(64),
  metadata                 jsonb not null default '{}',
  created_at               timestamptz(6) not null,
  created_by               varchar(255) not null,
  updated_at               timestamptz(6) not null,
  updated_by               varchar(255) not null,
  deleted_at               timestamptz(6),
  deleted_by               varchar(255),
  version                  integer not null,
  -- Employment references an existing Person (AD-001, §37). This is the one foreign key that
  -- crosses a module's tables, and it points *backward*, to a module Employment already depends
  -- on. `identity.employment_link` points forward to this table and deliberately carries no key,
  -- which is the same rule rather than a different one — ADR-0042.
  constraint employment_person_fk foreign key (person_id) references person (id),
  constraint employment_status_check
    check (status in ('draft', 'pending_approval', 'active', 'suspended', 'ended')),
  -- An employment that started before the person was ever hired is a typing mistake, and it
  -- reaches a service-length calculation as a plausible number.
  constraint employment_hire_before_start_check check (original_hire_date <= start_date),
  constraint employment_end_after_start_check check (end_date is null or end_date >= start_date),
  -- Ended, dated and explained are one fact. An ended employment with no end date answers "when
  -- did they leave" with nothing, and one with no reason answers "why" with nothing — and both
  -- questions are asked by a final settlement, not by a screen.
  constraint employment_ended_is_dated_check check ((status = 'ended') = (end_date is not null)),
  constraint employment_ended_is_explained_check
    check ((status = 'ended') = (end_reason_code is not null))
);

create unique index employment_number_key
  on employment (tenant_id, employment_number)
  where deleted_at is null;

-- The customer's own number, unique where it is present. A migration that carried the same legacy
-- number onto two employments has a bug in the migration, and finding it here is cheaper than
-- finding it in a payroll file.
create unique index employment_external_number_key
  on employment (tenant_id, external_employee_number)
  where external_employee_number is not null and deleted_at is null;

-- One open employment per person. The deterministic half of the duplicate protection: the domain
-- refuses a second one, and this refuses it again when two requests race.
create unique index employment_one_open_per_person_key
  on employment (tenant_id, person_id)
  where status <> 'ended' and deleted_at is null;

create index employment_tenant_status_idx on employment (tenant_id, status);
create index employment_tenant_person_idx on employment (tenant_id, person_id);
create index employment_tenant_start_idx on employment (tenant_id, start_date);

-- ---------------------------------------------------------------------------------------------
-- Every status transition, appended and never amended.
--
-- The events are how other modules hear about a change; this is how the *database* answers "what
-- was this employment's status on that date". A consumer that subscribed after the fact cannot
-- replay an event stream, and an auditor is exactly that consumer.
-- ---------------------------------------------------------------------------------------------
create table employment_status_record (
  id             uuid primary key default app_uuid_v7(),
  tenant_id      uuid not null,
  employment_id  uuid not null,
  -- Absent on the first record, which is the creation itself.
  from_status    varchar(32),
  to_status      varchar(32) not null,
  reason_code    varchar(64),
  note           varchar(1024),
  effective_from timestamptz(6) not null,
  -- Taken from the authenticated context by infrastructure. A caller cannot supply it, which is
  -- what stops somebody recording a suspension as though a colleague had ordered it.
  recorded_by    varchar(255) not null,
  recorded_at    timestamptz(6) not null,
  created_at     timestamptz(6) not null,
  created_by     varchar(255) not null,
  updated_at     timestamptz(6) not null,
  updated_by     varchar(255) not null,
  deleted_at     timestamptz(6),
  deleted_by     varchar(255),
  version        integer not null,
  constraint employment_status_record_employment_fk
    foreign key (employment_id) references employment (id),
  constraint employment_status_record_to_check
    check (to_status in ('draft', 'pending_approval', 'active', 'suspended', 'ended')),
  constraint employment_status_record_moves_check check (from_status is distinct from to_status)
);

create index employment_status_record_employment_idx
  on employment_status_record (tenant_id, employment_id, effective_from);

-- ---------------------------------------------------------------------------------------------
-- Organizational placement, on a timeline.
-- ---------------------------------------------------------------------------------------------
create table employment_assignment (
  id              uuid primary key default app_uuid_v7(),
  tenant_id       uuid not null,
  employment_id   uuid not null,
  -- `organization`'s unit, position and cost centre, referenced by identity only. No foreign key
  -- crosses to them: a composite key enforcing the tenant would need a new unique index on
  -- Organization's tables, and Employment does not reshape a completed module's schema. Tenant
  -- containment rests on row-level security, which makes another tenant's row unreadable.
  unit_id         uuid not null,
  position_id     uuid,
  cost_center_id  uuid,
  assignment_type varchar(16) not null,
  -- Full-time equivalent for this assignment alone: a share of a working pattern, never a share
  -- of a salary. Compensation is Phase 10's and nothing here is money.
  fte             numeric(5, 4) not null,
  reason_code     varchar(64),
  effective_from  timestamptz(6) not null,
  effective_to    timestamptz(6),
  created_at      timestamptz(6) not null,
  created_by      varchar(255) not null,
  updated_at      timestamptz(6) not null,
  updated_by      varchar(255) not null,
  deleted_at      timestamptz(6),
  deleted_by      varchar(255),
  version         integer not null,
  constraint employment_assignment_employment_fk
    foreign key (employment_id) references employment (id),
  constraint employment_assignment_type_check check (assignment_type in ('primary', 'secondary')),
  constraint employment_assignment_fte_check check (fte > 0 and fte <= 1),
  -- A period of no duration answers "where did they work on that date" with a period nothing is
  -- in. The same rule Phase 3 and Phase 4 arrived at, inherited rather than rediscovered.
  constraint employment_assignment_period_check
    check (effective_to is null or effective_to > effective_from)
);

-- One open primary assignment. §15 and §37 both require this, and §37 requires it here as well as
-- in the domain — two simultaneous primaries is not a display problem, it is two answers to
-- "which department is this person in" and the system must be incapable of holding both.
create unique index employment_assignment_one_primary_key
  on employment_assignment (tenant_id, employment_id)
  where assignment_type = 'primary' and effective_to is null and deleted_at is null;

create index employment_assignment_employment_idx
  on employment_assignment (tenant_id, employment_id, effective_from);
create index employment_assignment_unit_idx on employment_assignment (tenant_id, unit_id);
-- The index the filled-headcount adapter reads: Organization asks how many assignments exist
-- against a position in a unit on a date, and this is that question's shape.
create index employment_assignment_position_unit_idx
  on employment_assignment (tenant_id, position_id, unit_id);
create index employment_assignment_center_idx on employment_assignment (tenant_id, cost_center_id);

-- ---------------------------------------------------------------------------------------------
-- The managerial relationship, on a timeline.
--
-- A manager is an *employment*, not a second identity. That is what keeps "who was this person's
-- manager in March" answerable after the manager themselves has changed jobs twice.
-- ---------------------------------------------------------------------------------------------
create table employment_reporting_line (
  id                    uuid primary key default app_uuid_v7(),
  tenant_id             uuid not null,
  employment_id         uuid not null,
  manager_employment_id uuid not null,
  line_type             varchar(16) not null,
  effective_from        timestamptz(6) not null,
  effective_to          timestamptz(6),
  created_at            timestamptz(6) not null,
  created_by            varchar(255) not null,
  updated_at            timestamptz(6) not null,
  updated_by            varchar(255) not null,
  deleted_at            timestamptz(6),
  deleted_by            varchar(255),
  version               integer not null,
  constraint employment_reporting_line_employment_fk
    foreign key (employment_id) references employment (id),
  constraint employment_reporting_line_manager_fk
    foreign key (manager_employment_id) references employment (id),
  constraint employment_reporting_line_type_check check (line_type in ('primary', 'functional')),
  -- Reporting to yourself is a cycle of length one, and it is the one the database can catch.
  -- Longer cycles are a domain rule, because a walk is not a constraint.
  constraint employment_reporting_line_not_self_check
    check (manager_employment_id <> employment_id),
  constraint employment_reporting_line_period_check
    check (effective_to is null or effective_to > effective_from)
);

create unique index employment_reporting_line_one_primary_key
  on employment_reporting_line (tenant_id, employment_id)
  where line_type = 'primary' and effective_to is null and deleted_at is null;

create index employment_reporting_line_employment_idx
  on employment_reporting_line (tenant_id, employment_id, effective_from);
create index employment_reporting_line_manager_idx
  on employment_reporting_line (tenant_id, manager_employment_id);

-- ---------------------------------------------------------------------------------------------
-- The contract, on a timeline.
--
-- Terms as recorded, never as computed. `notice_period_days` is what the parties agreed; the
-- statutory minimum that may override it belongs to a country pack (Phase 11.1), and a schema
-- that computed one here would be labour law hardcoded in a table.
-- ---------------------------------------------------------------------------------------------
create table employment_contract (
  id                     uuid primary key default app_uuid_v7(),
  tenant_id              uuid not null,
  employment_id          uuid not null,
  contract_number        varchar(64),
  contract_type_code     varchar(64) not null,
  start_date             date not null,
  end_date               date,
  probation_end_date     date,
  probation_outcome      varchar(16),
  notice_period_days     integer,
  working_hours_per_week numeric(5, 2),
  -- A reference into the document store, never bytes in a row. Employment builds no document
  -- management (§24).
  document_reference     varchar(128),
  effective_from         timestamptz(6) not null,
  effective_to           timestamptz(6),
  created_at             timestamptz(6) not null,
  created_by             varchar(255) not null,
  updated_at             timestamptz(6) not null,
  updated_by             varchar(255) not null,
  deleted_at             timestamptz(6),
  deleted_by             varchar(255),
  version                integer not null,
  constraint employment_contract_employment_fk
    foreign key (employment_id) references employment (id),
  constraint employment_contract_end_check check (end_date is null or end_date >= start_date),
  constraint employment_contract_probation_check
    check (probation_end_date is null or probation_end_date >= start_date),
  -- No `failed`: a failed probation ends the employment, which is a status transition with its own
  -- reason and its own audit, not an outcome recorded quietly on a contract row.
  constraint employment_contract_outcome_check
    check (probation_outcome is null or probation_outcome in ('pending', 'passed', 'waived')),
  constraint employment_contract_notice_check
    check (notice_period_days is null or notice_period_days >= 0),
  constraint employment_contract_hours_check
    check (working_hours_per_week is null or working_hours_per_week > 0),
  constraint employment_contract_period_check
    check (effective_to is null or effective_to > effective_from)
);

create unique index employment_contract_number_key
  on employment_contract (tenant_id, contract_number)
  where contract_number is not null and deleted_at is null;

create index employment_contract_employment_idx
  on employment_contract (tenant_id, employment_id, effective_from);
create index employment_contract_probation_idx
  on employment_contract (tenant_id, probation_end_date);

-- ---------------------------------------------------------------------------------------------
-- Row-level security (ADR-0030).
--
-- Every table here carries `tenant_id`, so every one takes the standard policy. There is no
-- exception in this module.
-- ---------------------------------------------------------------------------------------------
call app_protect_table('employment');
call app_protect_table('employment_status_record');
call app_protect_table('employment_assignment');
call app_protect_table('employment_reporting_line');
call app_protect_table('employment_contract');
call app_protect_table('employment_number_sequence');

comment on table employment is
  'One employment relationship between a Person and this tenant. References Person; Person never references Employment (AD-001). Holds no organizational placement — that is employment_assignment (AD-005) — no attendance, no leave balance and no payroll calculation.';
comment on column employment.employment_number is
  'Generated by this product, tenant-scoped, immutable and never reused. Not the person''s identity: a rehire is a new employment with a new number and the same Person (AD-002, ADR-0039).';
comment on column employment.external_employee_number is
  'The customer''s own number, carried through a migration. Never generated here, and never treated as identity.';
comment on column employment.original_hire_date is
  'The first day this human being ever worked for this tenant, copied forward across a rehire and never recomputed. Service-length entitlements in several of this product''s markets are measured from it.';
comment on table employment_assignment is
  'Where an employment sits in the organization, and from when. Never edited: a transfer closes one period and opens another. No work-location column — a unit and a physical place of work are different concepts and this product holds no authoritative model of the second (ADR-0041).';
comment on table employment_reporting_line is
  'Who this employment reported to, and from when. A manager is an employment rather than a second identity, which is what keeps the question answerable after the manager has changed jobs.';
comment on table employment_number_sequence is
  'The tenant-scoped counter employment numbers are drawn from. A table rather than a sequence: a sequence is neither tenant-scoped nor transactional, and a rolled-back create would leave a permanent gap in a customer''s numbering.';
