/**
 * Learning and development: the course catalogue and its versions, learning paths, mandatory
 * training requirements, assignments, enrolments, assessments and certifications.
 *
 * **This module records what somebody attained and evaluates nobody.** It writes no capability to
 * People, no rating to Performance and no status to Employment. What somebody *claims* is People's
 * record, what a manager *observed of the job* is Performance's, and what they *attained* is this
 * one — AD-002 says course completion does not imply competency, and no column here implies it
 * either. Performance, Compensation and Career pull a completion or a certification when they want
 * one (AD-005).
 *
 * **Two questions are answered by computation rather than by a stored flag.** Whether an assignment
 * is overdue, and whether a certification is still valid, are functions of a date and the day
 * somebody asked — because `JobPort` has no adapter anywhere in this repository, and a flag nothing
 * maintains would show `valid` for a licence that lapsed in March (ADR-0070, ADR-0071).
 *
 * **This module invents no scoring formula.** The specification names five assessment kinds and
 * defines no threshold, weighting, rounding or attempt policy, so an authorized assessor records an
 * outcome and nothing here computes one. Aggregate assessment scoring is `NOT VERIFIED`.
 *
 * **Nothing here is scheduled.** Recurring training is generated by a bounded, idempotent command an
 * administrator runs. Scheduled execution is `NOT VERIFIED`.
 */
export * from './domain/learning-vocabulary.js';
export * from './domain/learning-rejection.js';
export * from './domain/course.js';
export * from './domain/enrolment.js';
export * from './domain/assignment.js';
export * from './domain/certification.js';
export * from './domain/assessment.js';
export * from './domain/mandatory-rule.js';
export * from './domain/path.js';
export * from './domain/instructor.js';

export * from './contracts/views.js';

export { learningModule } from './application/learning-module.js';
export {
  ALL_LEARNING_PERMISSIONS,
  LearningPermissions,
  UNROUTED_LEARNING_PERMISSIONS,
} from './application/learning-permissions.js';
export type { LearningPermission } from './application/learning-permissions.js';

export type { LearningDependencies } from './application/learning-dependencies.js';

/**
 * The ports, as types. The composition root implements them against the owning modules' published
 * queries under bounded service grants (ADR-0043); a concrete adapter exported from here would be
 * this module deciding how another module is read.
 *
 * `documentsUnavailable` is exported as a *value* because it is not an adapter — it is the accurate
 * statement that nothing resolves a document reference in this repository, and a composition root
 * that has no better answer should install it rather than invent one.
 */
export { documentsUnavailable } from './application/learning-ports.js';
export type {
  Audience,
  Clock,
  DocumentReferencePort,
  EmploymentFacts,
  EmploymentPort,
  LearningStores,
  NotificationIntentPort,
  OrganizationPort,
} from './application/learning-ports.js';

/**
 * The PostgreSQL stores, for the composition root.
 *
 * Exported as a factory rather than as the repository classes: a consumer that could construct one
 * repository could construct a partial store set, and `LearningStores` is the interface the module
 * actually needs.
 */
export { postgresLearningStores } from './infrastructure/learning-stores.js';

/**
 * The transport: the controllers, and the injectable the composition root binds the dispatcher to.
 *
 * The controllers are exported rather than a Nest module, because the module that declares them
 * lives beside the composition root — the order they are declared in is load-bearing for route
 * resolution, and that ordering belongs with the application that serves them.
 */
export { LearningDispatcher } from './api/learning-dispatcher.js';
export { LearningCourseCategoryController } from './api/course-category.controller.js';
export { LearningCourseController } from './api/catalogue.controller.js';
export {
  LearningAssessmentController,
  LearningCourseVersionController,
} from './api/assessment.controller.js';
export { LearningPathController } from './api/path.controller.js';
export { LearningMandatoryRuleController } from './api/mandatory-rule.controller.js';
export { LearningAssignmentController } from './api/assignment.controller.js';
export { LearningEnrolmentController } from './api/enrolment.controller.js';
export { LearningEnrolmentLifecycleController } from './api/enrolment-lifecycle.controller.js';
export { LearningCertificationController } from './api/certification.controller.js';
export { LearningInstructorController } from './api/instructor.controller.js';
export { LearningHistoryController } from './api/history.controller.js';
