import type { PermissionChecker, UnitOfWork } from '@work/kernel';

import type {
  Clock,
  LetterSources,
  LettersStores,
  VerificationTokenPort,
} from './letters-ports.js';

/**
 * Everything this module needs from outside itself, in one place.
 *
 * **No renderer and no signature provider.** Neither exists in this repository, and declaring a port
 * for either would imply this module could reach one. A letter's *content* — the frozen substituted
 * values and the template version — is fully owned and reproducible without a renderer; only the
 * artefact is missing, and it is recorded as missing rather than approximated (D-15, D-16).
 *
 * `permissions` is here because generation has to ask: a template that exposes salary may only be
 * generated by a requester who holds `letter.include-salary`, which is the second of AD-005's two
 * gates and cannot be checked by the pipeline's single per-handler permission.
 */
export interface LettersDependencies {
  readonly unitOfWork: UnitOfWork;
  readonly stores: LettersStores;
  readonly sources: LetterSources;
  readonly tokens: VerificationTokenPort;
  readonly permissions: PermissionChecker;
  readonly clock: Clock;
}
