import type { ReactNode } from 'react';
import type { AssignmentView, MandatoryRuleView } from '@work/learning/contracts';

import { civil, count } from './exact';
import { ruleActionsFor, ruleWithheldBecause } from './lifecycle';
import {
  Actions,
  Empty,
  Section,
  Status,
  Table,
  named,
  short,
  type SectionProps,
} from './sections';

/**
 * What a tenant made mandatory, of whom, and what past reconciliation runs actually produced.
 *
 * **Nothing schedules any of this, and the screen says so rather than implying it.** Recurring
 * training is generated by a bounded, idempotent command an administrator runs: `JobPort` has no
 * adapter anywhere in this repository, so there is no next-run time to display and no "last run"
 * column, because no run is recorded as an event. Scheduled execution is `NOT VERIFIED`, and a
 * screen showing a schedule would be promising something nothing performs.
 *
 * **What a run produced is visible in the assignments it generated.** That is the honest artefact:
 * each generated requirement carries the rule that produced it and the occurrence it belongs to, so
 * the occurrences already opened are the observable history of reconciliation. The counts here are
 * over the assignment **page** the screen fetched, and the note says so — a compliance count that
 * silently described fifty rows of four thousand would be worse than no count at all.
 *
 * **An audience is shown as the rule states it**, never resolved here. A rule over an organization
 * unit covers whoever is in that unit at the moment somebody reconciles it, which is why a person
 * who transfers in tomorrow is covered without anybody editing anything — and why this screen
 * cannot show a membership list without asking Organization a question it has not been given
 * permission to ask.
 */

/**
 * One requirement, as a row.
 *
 * Its own component because the audience cell is three fields in one — the kind, and whichever of a
 * unit or a position the rule names — and because the generated count is deliberately page-scoped.
 * Both are the kind of thing that acquires a quiet second meaning when it lives inside a table body.
 */
const RuleRow = ({
  t,
  language,
  rule,
  assignments,
}: SectionProps & {
  readonly rule: MandatoryRuleView;
  readonly assignments: readonly AssignmentView[];
}): ReactNode => (
  <tr>
    <td>{named(rule.name, language)}</td>
    <td>
      <Status t={t} group="mandatoryKind" status={rule.kind} />
    </td>
    <td>
      <Status t={t} group="audienceKind" status={rule.audience} />
      {rule.organizationUnitId === undefined ? undefined : ` · ${short(rule.organizationUnitId)}`}
      {rule.positionId === undefined ? undefined : ` · ${short(rule.positionId)}`}
    </td>
    {/* A civil date, exactly as stored. Never parsed into a `Date` to be reformatted. */}
    <td>{civil(rule.effectiveFrom)}</td>
    <td>{count(rule.recurrenceMonths)}</td>
    <td>{count(rule.dueWithinDays)}</td>
    <td>
      <Status t={t} group="ruleState" status={rule.active ? 'active' : 'retired'} />
    </td>
    <td>{count(generatedBy(rule, assignments))}</td>
  </tr>
);

export const RulesSection = ({
  t,
  language,
  rules,
  assignments,
  total,
}: SectionProps & {
  readonly rules: readonly MandatoryRuleView[];
  readonly assignments: readonly AssignmentView[];
  readonly total: number;
}): ReactNode => (
  <Section
    t={t}
    title="compliance"
    total={total}
    shown={rules.length}
    note="learning.notice.countsAreOfThisPage"
  >
    {rules.length === 0 ? (
      <Empty t={t} />
    ) : (
      <>
        <Table
          t={t}
          headers={[
            'title',
            'kind',
            'audience',
            'effectiveFrom',
            'recurrence',
            'dueWithin',
            'active',
            'generated',
          ]}
        >
          {rules.map((rule) => (
            <RuleRow
              key={rule.mandatoryRuleId}
              t={t}
              language={language}
              rule={rule}
              assignments={assignments}
            />
          ))}
        </Table>

        <Actions
          t={t}
          actions={ruleActionsFor(rules[0])}
          withheld={ruleWithheldBecause(rules[0])}
        />
      </>
    )}
  </Section>
);

/** How many of the fetched assignments this rule generated. Of the page, and labelled as such. */
const generatedBy = (rule: MandatoryRuleView, assignments: readonly AssignmentView[]): number =>
  assignments.filter((assignment) => assignment.mandatoryRuleId === rule.mandatoryRuleId).length;

/**
 * The reconciliation position: which occurrences a rule has already opened.
 *
 * **This is what a run produced, not a run log.** Nothing records a reconciliation as an event — the
 * command is idempotent and its result is the rows it created — so the honest artefact is the set
 * of occurrence days already opened, each of which is a requirement somebody carries. An occurrence
 * key is a civil date derived from the rule's own recurrence, not a counter (ADR-0071), and it is
 * rendered exactly as the API sent it.
 *
 * The note states plainly that nothing runs this on a schedule.
 */
export const ReconciliationSection = ({
  t,
  language,
  rules,
  assignments,
  asOf,
}: SectionProps & {
  readonly rules: readonly MandatoryRuleView[];
  readonly assignments: readonly AssignmentView[];
  readonly asOf: string | undefined;
}): ReactNode => {
  const generated = assignments.filter((assignment) => assignment.source === 'mandatory_rule');

  return (
    <Section t={t} title="reconciliation" note="learning.notice.notScheduled">
      <p className="text-xs opacity-70">{`${t('learning.label.asOf')}: ${civil(asOf)}`}</p>

      {generated.length === 0 ? (
        <Empty t={t} />
      ) : (
        <Table t={t} headers={['title', 'occurrence', 'employment', 'dueOn', 'status', 'overdue']}>
          {generated.map((assignment) => (
            <tr key={assignment.assignmentId}>
              <td>{named(ruleFor(assignment, rules)?.name, language)}</td>
              <td>{civil(assignment.occurrenceKey)}</td>
              <td>{short(assignment.employmentId)}</td>
              <td>{civil(assignment.dueOn)}</td>
              <td>
                <Status t={t} group="assignmentStatus" status={assignment.status} />
              </td>
              <td>
                <Status t={t} group="answer" status={assignment.overdue ? 'yes' : 'no'} />
              </td>
            </tr>
          ))}
        </Table>
      )}
    </Section>
  );
};

/** The rule an assignment names, from the page already fetched. Never a request per row. */
const ruleFor = (
  assignment: AssignmentView,
  rules: readonly MandatoryRuleView[],
): MandatoryRuleView | undefined =>
  rules.find((rule) => rule.mandatoryRuleId === assignment.mandatoryRuleId);
