import { accept, refuse, type EmploymentResult } from './employment-rejection.js';

/**
 * The employment number: what a customer calls somebody in a payroll file, on a badge and in a
 * government submission.
 *
 * **It is generated by this product and never supplied by a caller** (ADR-0039). That is the whole
 * decision, and it exists because the alternative — a caller-supplied number — makes three
 * guarantees impossible at once: uniqueness within the tenant, immutability, and never being
 * reused after an employment ends. A customer's own number still travels, in
 * `externalEmployeeNumber` beside it, which is what lets a migration keep its legacy references
 * without either value pretending to be the person's identity.
 *
 * **It is not identity.** A person rehired four years later is the same Person with a *new*
 * employment and a *new* number (AD-002, AD-004). Anything that joins on an employment number is
 * joining on an employment, not on a human being, and a system that confused the two would merge
 * two careers the first time somebody returned.
 *
 * The series is the calendar year of the employment's **start date**, so `EMP-2026-000123` reads
 * as the hundred-and-twenty-third employment starting in 2026. A back-dated hire draws from its
 * own year's series, which is what makes the number mean what it appears to mean.
 */

const PREFIX = 'EMP';
const WIDTH = 6;

/**
 * The pattern a generated number matches.
 *
 * Anchored and checked on the way *in* as well as on the way out: a row that somehow acquired a
 * number of another shape — a migration, a fixture, a hand-written insert — is a row this module
 * must not silently accept as its own.
 */
const PATTERN = /^EMP-\d{4}-\d{6,}$/;

export const isEmploymentNumber = (value: string): boolean => PATTERN.test(value);

/**
 * Which counter a number is drawn from. One series per tenant per year — the tenant scoping is the
 * sequence table's, and this is only the key within it.
 */
export const seriesKeyFor = (startDate: string): string => startDate.slice(0, 4);

/**
 * Formats an allocated counter value.
 *
 * Numbers past 999999 widen rather than wrap. Wrapping would reuse a number, and reuse is the one
 * thing this design refuses outright: a reused number resolves a payroll file, an archived payslip
 * and a government submission to the wrong person, years after anybody could notice.
 */
export const employmentNumberFrom = (seriesKey: string, value: number): string =>
  `${PREFIX}-${seriesKey}-${String(value).padStart(WIDTH, '0')}`;

/** A number read back from the database, checked rather than trusted. */
export const checkedEmploymentNumber = (value: string): EmploymentResult<string> =>
  isEmploymentNumber(value) ? accept(value) : refuse('employment_number_malformed');

/**
 * The customer's own reference, if they carried one across.
 *
 * Looser than an entity code on purpose: a legacy number is whatever the system it came from used,
 * and refusing a customer's twenty-year-old numbering scheme at import is refusing the migration.
 * It is stored, indexed for uniqueness, and never interpreted.
 */
export const checkedExternalNumber = (
  value: string | undefined,
): EmploymentResult<string | undefined> => {
  if (value === undefined) return accept(undefined);

  const trimmed = value.trim();

  if (trimmed === '') return accept(undefined);
  if (trimmed.length > 64) return refuse('text_too_long', { field: 'externalEmployeeNumber' });
  return accept(trimmed);
};
